### ISSUE TITLE
Cannot start a stopped/crash Home Assistant instance

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-cli#87]
**Describe the bug**

The CLI does not allow me to bring up a Home Assistant instance that is down.

**Steps to reproduce**
1. Make a configuration error in Home Assistant
1. Call `hassio ha restart`
1. Home Asssistant will fail.

Try to get it running again, which will fail:
- `hassio ha start`
- `hassio ha restart`

Error message:

```txt
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x6b7a80, 0xc42006e8c0)
        /home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0xc420112200, 0x24, 0x200, 0x0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x32e
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x704913, 0xd, 0x7ffe62828dd3, 0x7, 0x0, 0x0, 0xc420069300, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x13d
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0xc42008ab00)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x286
github.com/urfave/cli.HandleAction(0x69be20, 0x729be0, 0xc42008ab00, 0x0, 0xc420066a20)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0x7c
github.com/urfave/cli.Command.Run(0x704913, 0xd, 0x0, 0x0, 0x85a6c0, 0x1, 0x1, 0x70f806, 0x2f, 0x0, ...)
        /home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x5a5
github.com/urfave/cli.(*App).Run(0xc4200ea000, 0xc42006a0c0, 0x3, 0x3, 0x0, 0x0)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x7fa
main.main()
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x145
```

**Debug info**
1. SSH Addon type:
- [X] Community
- [X] Core
- [X] Custom

2. Output of `hassio --version`

hassio version 1.3.1

3. Version of hassio / homeassistant

0.72

4. Output from executing the command with debug info.

```txt
hassio -d ha restart
DEBUG [CmdHomeassistant]: action->'restart', endpoint='restart', serverOverride->'', GET->'false', options->'', rawjson->'fa
lse', filter->''
DEBUG [ExecCommand]: basepath->'homeassistant', endpoint->'restart', serverOverride->'', get->'false', Options->'', Filter->
'', RawJSON->'false'
DEBUG [GenerateURI]: basepath->'homeassistant', endpoint->'restart', serverOverride->''
DEBUG [RestCall]: data->'http://hassio/homeassistant/restart', GET->'false', payload->''
DEBUG [RestCall]: ResponseBody->'{"result": "error", "message": null}'
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x6b7a80, 0xc420116140)
        /home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0xc42011e000, 0x24, 0x200, 0x0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x32e
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x704913, 0xd, 0x7ffc529dfd75, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0
, 0x0, ...)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x13d
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0xc42008a9a0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x286
github.com/urfave/cli.HandleAction(0x69be20, 0x729be0, 0xc42008a9a0, 0x0, 0xc420070a20)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0x7c
github.com/urfave/cli.Command.Run(0x704913, 0xd, 0x0, 0x0, 0x85a6c0, 0x1, 0x1, 0x70f806, 0x2f, 0x0, ...)
        /home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x5a5
github.com/urfave/cli.(*App).Run(0xc42000c380, 0xc42000a100, 0x4, 0x4, 0x0, 0x0)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x7fa
main.main()
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x145
```

**Expected behavior**

Home Assistant should start.

**Additional context**

The funny thing is... The old CLI just saves the day:

`curl -s -X POST -H "X-HASSIO-KEY: ${HASSIO_TOKEN}" "http://hassio/homeassistant/restart"`

**Classification**

I think the severity and impact of this issue are high. New users will now not have a way to revive Home Assistant after they have caused an error. This might result in "pull-the-power" style reboots, which can be problematic for the Pi.

Secondly, it will frustrate the user and giving them a bad feeling / first time experience (since it is likely a new user WILL make an error).

**Comment by smnino** [comment]
franc hit the nail on the head. I'm a fairly new user and this has really frustrated me and led me to pull the power more than once as I know of no other way to get the system responding again. 

I discovered this issue when trying to update from Hassio .71 to .72. The web UI simply doesn't respond so I went to the CLI to try that route in hopes if at least seeing something in the logs. Update fails with the error already reported in this post.

**Comment by pvizeli** [comment]
Do you see any things in su logs @frenck ?

**Comment by ryanm101** [comment]
SO i'm running 0.69.1 and `hassio ha restart` works as expected. 

Are you on resinOS or hassioOS?

**Comment by frenck** [comment]
Generic Linux, minimal/clean installation, recently updated by the latest installer.

**Comment by ryanm101** [comment]
I've tried it on your vagrant version and it works as expected as well. (amd_64)

**Comment by ryanm101** [comment]
Anyway you can get me access to a box it fails on? or make it reproducible in vagrant?

**Comment by frenck** [comment]
I'm in the middle of re-installing everything (getting in a new 500GB SDD 🎉 ), I'll report back later.

**Comment by ryanm101** [comment]
nice.. :) Thanks.

**Comment by pdecat** [comment]
Same issue here with update and restart commands:

```
➜  ~ hassio ha update
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x6b7a80, 0xc42003ca00)
        /home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0xc4200c4400, 0x24, 0x200, 0x0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x32e
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x704913, 0xd, 0x7ffce1af4d79, 0x6, 0x0, 0x0, 0xc42000f400, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x13d
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0xc4200629a0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x286
github.com/urfave/cli.HandleAction(0x69be20, 0x729be0, 0xc4200629a0, 0x0, 0xc420048a80)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0x7c
github.com/urfave/cli.Command.Run(0x704913, 0xd, 0x0, 0x0, 0x85a6c0, 0x1, 0x1, 0x70f806, 0x2f, 0x0, ...)
        /home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x5a5
github.com/urfave/cli.(*App).Run(0xc4200bc000, 0xc42000a120, 0x3, 0x3, 0x0, 0x0)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x7fa
main.main()
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x145
➜  ~ hassio ha restart
ERROR
panic: interface conversion: interface is nil, not string

goroutine 1 [running]:
panic(0x6b7a80, 0xc42003ca00)
        /home/travis/.gimme/versions/go1.7.6.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/home-assistant/hassio-cli/command/helpers.DisplayOutput(0xc4200c4400, 0x24, 0x200, 0x0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:118 +0x32e
github.com/home-assistant/hassio-cli/command/helpers.ExecCommand(0x704913, 0xd, 0x7ffc5af17d78, 0x7, 0x0, 0x0, 0xc42000f400, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/helpers/common.go:155 +0x13d
github.com/home-assistant/hassio-cli/command.CmdHomeassistant(0xc4200629a0)
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/command/homeassistant.go:48 +0x286
github.com/urfave/cli.HandleAction(0x69be20, 0x729be0, 0xc4200629a0, 0x0, 0xc420048a20)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:503 +0x7c
github.com/urfave/cli.Command.Run(0x704913, 0xd, 0x0, 0x0, 0x85a6c0, 0x1, 0x1, 0x70f806, 0x2f, 0x0, ...)
        /home/travis/gopath/src/github.com/urfave/cli/command.go:165 +0x5a5
github.com/urfave/cli.(*App).Run(0xc4200bc000, 0xc42000a120, 0x3, 0x3, 0x0, 0x0)
        /home/travis/gopath/src/github.com/urfave/cli/app.go:259 +0x7fa
main.main()
        /home/travis/gopath/src/github.com/home-assistant/hassio-cli/main.go:22 +0x145
```


The corresponding error in the supervisor logs is:

```
18-07-01 20:30:17 ERROR (MainThread) [hassio.utils] Can't excute update while a task is in progress
18-07-01 20:31:35 ERROR (MainThread) [hassio.utils] Can't excute restart while a task is in progress
```

**Comment by frenck** [comment]
Hmmm that might be part of the issue, which might not be CLI related.

Restart HA via Hass.io, the API will probably wait for a sign of life?

**Comment by pvizeli** [comment]
A problem could be, that you can send a command to home-assistant, if there is already a command in progress. That would be stay in log.

**Comment by pdecat** [comment]
Shouldn't the CLI handle this properly and display a message instead of panicking?

**Comment by ryanm101** [comment]
@pdecat ideally yes, but I can only handle errors i have encountered. :)

@pvizeli Usually the CLI hangs until the command returns complete, I could maybe simulate by opening two console sessions, but i would need a long running command. 

Whats weird is I cannot reproduce any of the issues reported since 1.3.1.

I've an RPI running an old version of resinOS + hassio and I'm trying to reproduce on @frenck hassio-vagrant.

**Comment by ryanm101** [comment]
So if anyone can get me an env that has the issue I'd be happy to solve the problem.

**Comment by pdecat** [comment]
How I ended up in this situation is upgrading from 0.72.1 to the broken [0.73.0b0](https://github.com/home-assistant/home-assistant/issues/15229) from hassio UI.

The watchdog will notice it is broken then stop and start it in loop.
During that time, the above mentioned errors occur:

```
18-07-01 19:28:20 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-07-01 19:28:20 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/qemux86-64-homeassistant docker application
18-07-01 19:28:20 INFO (SyncWorker_1) [hassio.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.73.0b0
18-07-01 19:38:21 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-07-01 19:38:35 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-07-01 19:38:35 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/qemux86-64-homeassistant docker application
18-07-01 19:38:35 INFO (SyncWorker_1) [hassio.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.73.0b0
18-07-01 19:48:36 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-07-01 19:48:50 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-07-01 19:48:50 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/qemux86-64-homeassistant docker application
18-07-01 19:48:51 INFO (SyncWorker_1) [hassio.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.73.0b0
18-07-01 19:58:51 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-07-01 19:59:06 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-07-01 19:59:06 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/qemux86-64-homeassistant docker application
18-07-01 19:59:06 INFO (SyncWorker_1) [hassio.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.73.0b0
18-07-01 20:01:38 INFO (MainThread) [hassio.api.security] /homeassistant/update access from a0d7b954_ssh
18-07-01 20:01:38 ERROR (MainThread) [hassio.utils] Can't excute update while a task is in progress
18-07-01 20:09:06 WARNING (MainThread) [hassio.homeassistant] Don't wait anymore of Home-Assistant startup!
18-07-01 20:09:21 WARNING (MainThread) [hassio.tasks] Watchdog found a problem with Home-Assistant docker!
18-07-01 20:09:21 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/qemux86-64-homeassistant docker application
18-07-01 20:09:21 INFO (SyncWorker_1) [hassio.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.73.0b0
18-07-01 20:10:54 INFO (MainThread) [hassio.api.security] /homeassistant/update access from a0d7b954_ssh
18-07-01 20:10:54 ERROR (MainThread) [hassio.utils] Can't excute update while a task is in progress
```

**Comment by msanchezt** [comment]
Same issue here.

**Comment by matt1** [comment]
New user. Same issue here. Reproduced twice trying to update configuration.yaml which requires restarts.  You make some changes, restart via the UI and..... then it never restarts.

Logging in via SSH and using hassio cli to try and manually restart does not help.

The panic is due a bad type assertion.  Using the "old" curl approach gives me this:

```
core-ssh:/config# curl -s -X POST -H "X-HASSIO-KEY: ${HASSIO_TOKEN}" "http://hassio/homeassistant/restart"
{"result": "error", "message": null}
```

Null message for the restart error - probably why the type assertion fails.  Same errors in hassio su logs - 

```
ERROR (MainThread) [hassio.utils] Can't excute restart while a task is in progress
```

I've put in a PR to fix the bad assertion, but the fact that home assistant just doesn't work is disappointing as I was hoping home assistant was more reliable than openhab, but so far I cant even get it to start.  :(

**Comment by pvizeli** [comment]
1) We should fix that on home assistant, a integration should be not block the startup of home assistant
2) After 10min he stop the startup and you should be able to interact again with homeassistant
3) A kill function would be not bad, like http://hassio/homeassistant/kill

**Comment by matt1** [comment]
Ok so I left it overnight.  `hassio ha start` leads to same golang panic, but there is no corresponding `ERROR (MainThread) [hassio.utils] Can't excute restart while a task is in progress` error in `hassio su logs` this time.

If I try the curl direct approach, I do not get an error, but it did not return in a reasonable amount of time either (over 10 mins).  Web UI still not available.

If I go and comment out zha from /config/configuration.yaml then `hassio host reboot` then eventually the web UI comes back, so appears to be a problem with zigbee initialisation.  There are no errors or anything in hassio ha logs apart from something saying it is taking more than 10 seconds.

**Comment by frenck** [comment]
This error has been fixed in version 1.4.0.
